#
#  (C) Copyright 2021 IBM Corporation.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

'"Create or update work item" service flow':
  'Create work item':
    input: 
      # tenantId info as param to call sync api.
      - infoHubTentantId: tw.local.workItem.businessObject.tenantId
      # workitem object info as payload to new a workitem.
      - workItemBody: tw.local.workItemBody
    output:
      # result after new a workitem, it's workitem id info.
      - createResult: tw.local.workItemOutput

  'Update work item':
    input: 
      # tenantId info as param to call sync api.
      - infoHubTentantId: tw.local.workItem.businessObject.tenantId
      # workitem id info to indicate which workitem should be updated.
      - workItemId: tw.local.workItem.businessObject.id
      # payload info used to update workitem's status.
      - workItemBody: tw.local.workItemBody
    output:
      # result after update a workitem, it's workitem id info.
      - updateResult: tw.local.workItemOutput

'"Get inventory info" service flow':
  'get by inventory id': 
    input:
      # tenantId info as param to execute GQL.
      - infoHubTentantId: tw.local.tenantId
      # GQL statement for query location and product info by inventory id.
      - gqlBody: tw.local.queryLocationAndPartNumberGQL
    output:
      # GQL query result.
      - gqlResult: tw.local.queryLocationAndPartNumberGQLOutput


'"Send request notice email" service flow':
  'Send email':
    input: 
      # comma separated list of email addresses of the To recipients.
      - sendTo: tw.local.requestForm.nodeManagerInfo.email
      # The body of the email.
      - emailBody: tw.local.emailBody
      # the subject of the email.
      - emailSubject: tw.local.emailSubject
